### PR TITLE
Introduces cmake build and build types.

### PR DESCRIPTION
**Pull request by dkopko**
Moves defines out to build commandline, for alternate build types.

### CODE REVIEW

**Comment by munificent** [comment]
Hi, this is pretty interesting, but probably isn't a good fit to land in the repo.

These defines appear in the book itself so need to be in the source code where the build script can find them.

Using CMake for the build isn't a bad idea, but I'm not familiar with it and I'd like to avoid having to learn a new thing in order to maintain this. :)

**Comment by dkopko** [comment]
OK, understood.  I was trying to provide having multiple binaries built at once under different configurations of defines, but it's totally do-able without using cmake.  I just didn't realize until now that there was a Makefile for clox as I hadn't seen one in the c/ directory, only the XCode project.  Even trying to extend the current Makefile to achieve this would not be possible because the common.h does not accept nor work around any defines inherited from the compiler invocation. What do you think of the the following pattern to allow the build to modify defines when building the release/debug variants?:

#if ! defined DEBUG_TRACE_GC
#define DEBUG_TRACE_GC 0
#endif 

(with corresponding code changes to say "#if DEBUG_TRACE_GC" instead of "#ifdef DEBUG_TRACE_GC" )

Thank you for this project, by the way.

**Comment by munificent** [comment]
> What do you think of the the following pattern to allow the build to modify defines when building the release/debug variants?

That's a good idea. It should be straightforward to do that without the guards appearing in the book.

**Comment by burritoOverflow** [comment]
I adopted a similar approach (`CMake` and modifying `defines` based on build type) [here](https://github.com/burritoOverflow/CraftingInterpretersBytecodeInterpreter/blob/master/CMakeLists.txt).

I dig your build approach here (I'm a novice at `CMake` and cobbled my build together)--going to borrow some of yours for fun. I especially like the approach of using `Make` to invoke `CMake`.

This is neat; Thanks for sharing!

**Pull request closed without merging**
