### PR TITLE
Update README.md with hlox

### PR DESCRIPTION
**Pull request by Thomas-Neill**
My Haskell implementation of Lox.

### CODE REVIEW

**Comment by egordorichev** [comment]
Maybe you should first finish it?

**Comment by aggsol** [comment]
Most of the linked ones are not finished, not even a parser. But the book is not finished yet so that is Ok.

**Comment by egordorichev** [comment]
But they are 99% percent will be not finished. And if they want to, they can read the source code. For example, i did my c and java loxes for a few times already.

**Comment by Thomas-Neill** [comment]
I'll be updating it with the book, like most of the other implementations.

**Comment by Thomas-Neill** [comment]
I'm stupid, sorry. I clicked on the Close and Comment... Anyways, I plan to update it on the same schedule as the book.

**Comment by Thomas-Neill** [comment]
I would like to note that it is now up to date with the book.

**Comment by munificent** [comment]
Groovy, thanks!

**Pull request merged**
