### PR TITLE
Edited prose on Logical Operators section

### PR DESCRIPTION
**Pull request by brainuser5705**
New to programming languages, please correct me if I'm wrong.

I was reading the *Logical Operators* section of *The Lox Language* chapter and was really confused with the return statements for the `and` and `or` expressions. In the original prose, it says for `and`: *"It returns the left operand if it's false, or the right operand otherwise"* and then the first example shows `true and false; // false.` which is definitely not the left operand.

So I decided to try to emulate the style of the text to fix that misunderstanding and also provided all the possible expressions.

**UPDATE:**

Misunderstanding alleviated, changes is now making the subject of the sentence clearer i.e. changing *it* to *operand*.

### CODE REVIEW

**Comment by chrisjbreisch** [comment]
> it says for `and`: _"It returns the left operand if it's false, or the right operand otherwise"_ and then the first example shows `true and false; // false.` which is definitely not the left operand.

But that's correct, isn't it? 

Let's take it a step at a time: "It returns the left operand if it's false". It isn't. So, what happens if the left operand is not false?

"or the right operand otherwise". So, since the left operand is not false, lox returns the right operand, which in this instance is false. So, "true and false" yields false.

**Comment by brainuser5705** [comment]
@chrisjbreisch Ah I see, thank you for the explanation. 

When I read it, I thought that *it* was referring to the expression not the operand itself.

I haven't implemented the interpreter yet, but I'm assuming that this would be the algorithm that it uses?

**Comment by chrisjbreisch** [comment]
@brainuser5705 - Yes, that's correct. Also, there's a point to the rather confusing wording. lox doesn't just return true and false for logical expressions, but returns the values from the expressions.

Lox is like most languages in that 0 is false, and anything non-zero is true.

So, in the case of 3 and 4, 3 is "not false", so we look at the right operand, in this case 4. Thus, the result of 3 and 4 is 4, not just "true".

Now, if it were 0 and 4. 0 equates to false, so we just return the left operand, 0. Thus, the result of 0 and 4 is 0.

**Comment by brainuser5705** [comment]
@chrisjbreisch Now the sentence makes much more sense. I've reverted my changes but decided to make another commit to change *it* to *operand*. 

Thanks for the comment, I really appreciate it!

**Pull request closed without merging**
