### PR TITLE
Add tail call optimisation

### PR DESCRIPTION
**Pull request by Moosemorals**
This is just for fun, hopefuly someone will like it.

I've updated clox to add [tall call optimisation](https://en.wikipedia.org/wiki/Tail_call).

The VM recognises when a OP_CALL is followed by an OP_RETURN and so replaces the current function with the new function, rather than adding the new function to the call stack.

I'm suprised at how little code this needs, it makes me think I'm missing something obvious.

Anyway. Love the book, keeping myself busy till the next chapter.

### CODE REVIEW

**Comment by assyrianic** [comment]
Good catch, typically compilers are the ones that implement tail call optimizations.

**Comment by Moosemorals** [comment]
Yeah, I saw the Lua VM (for example) has an OP_TAILCALL, but I couldn't work out how to spot call/return pairs at compile time without adding too much complexity to the compiler.

By updating the VM I can spot OP_CALL/OP_RETURN directly in the bytecode (and I'd need to add support for a TAILCALL instruction anyway).

**Comment by assyrianic** [comment]
interesting case there, did you profile the code concerning this?

**Comment by Moosemorals** [comment]
No, I'm not that organised :-)

In terms of speed, function calls will execute a few more instructions (for the tests), a tail call potentially many more (proportional to the number of parameters).

Tail calls aren't about speed though, they're about keeping the stack under control in deep (recursive) function call chains. (I'm really looking forward to closures next chapter, I want to play with a more functional programming style)

**Comment by munificent** [comment]
This is really cool!

I'm not sure where this should go. I can't land this as a PR because I don't intend to do tail call optimization in the book. One option would be to put the diff in a gist. Or perhaps you could fork the repo and land your change on your fork?

Either way, I'm always excited to see people make changes like this and start exploring. :)

**Comment by 0x7ffc** [comment]
I don't know if it's the right way, but this is what I do to emit OP_TAIL_CALL at compile time:
```c
static void returnStatement(Compiler *compiler) {
  //if (compiler->type == TYPE_SCRIPT) {}
  if (consume(compiler, TOKEN_SEMICOLON)) {
       emitReturn(compiler);
  } else {
       expression(compiler);
       consume(compiler, TOKEN_SEMICOLON);
	if (compiler->fn->chunk.count >= 2  &&
	    compiler->fn->chunk.code[compiler->fn->chunk.count - 2] == OP_CALL) {
	    compiler->fn->chunk.code[compiler->fn->chunk.count - 2] = OP_TAIL_CALL;
	} else {
	    emitByte(compiler, OP_RETURN);
	}
  }
}
```
And at run time:
```c
case OP_TAIL_CALL: {
      int argCount = READ_BYTE();
      ObjClosure *closure = AS_CLOSURE(peekN(argCount));
      frame->closure = closure;
      frame->ip = closure->fn->chunk.code;
      for (int i = 0; i <= argCount; i++) {
        frame->slots[i] = peekN(argCount - i);
      }
      vm->sp = frame->slots + argCount + 1;
      ip = frame->ip;
      break;
    }
```

**Pull request closed without merging**
